//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Shell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToMostRecentlyUsedList cannot be changed while dialog is showing..
        /// </summary>
        public static string AddToMostRecentlyUsedListCannotBeChanged {
            get {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysAppendDefaultExtension cannot be changed while dialog is showing..
        /// </summary>
        public static string AlwaysAppendDefaultExtensionCannotBeChanged {
            get {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogComboBox..
        /// </summary>
        public static string ComboBoxIndexOutsideBounds {
            get {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name not available - dialog was canceled..
        /// </summary>
        public static string CommonFileDialogCanceled {
            get {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell item could not be created..
        /// </summary>
        public static string CommonFileDialogCannotCreateShellItem {
            get {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle provided cannot be IntPtr.Zero..
        /// </summary>
        public static string CommonFileDialogInvalidHandle {
            get {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected - the FileNames property should be used instead..
        /// </summary>
        public static string CommonFileDialogMultipleFiles {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected - the Items property should be used instead..
        /// </summary>
        public static string CommonFileDialogMultipleItems {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name not available - dialog has not closed yet..
        /// </summary>
        public static string CommonFileDialogNotClosed {
            get {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common File Dialog requires Windows Vista or later..
        /// </summary>
        public static string CommonFileDialogRequiresVista {
            get {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Files.
        /// </summary>
        public static string CommonFiltersOffice {
            get {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Picture Files.
        /// </summary>
        public static string CommonFiltersPicture {
            get {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files.
        /// </summary>
        public static string CommonFiltersText {
            get {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePrompt cannot be changed while dialog is showing..
        /// </summary>
        public static string CreatePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom controls cannot be removed from a File dialog once added..
        /// </summary>
        public static string DialogControlCollectionCannotRemoveControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control name cannot be null or zero length..
        /// </summary>
        public static string DialogControlCollectionEmptyName {
            get {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls..
        /// </summary>
        public static string DialogControlCollectionMenuItemControlsCannotBeAdded {
            get {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        public static string DialogControlCollectionModifyingControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot have more than one control with the same name..
        /// </summary>
        public static string DialogControlCollectionMoreThanOneControl {
            get {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog control must be removed from current collections first..
        /// </summary>
        public static string DialogControlCollectionRemoveControlFirst {
            get {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureFileExists cannot be changed while dialog is showing..
        /// </summary>
        public static string EnsureFileExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsurePathExists cannot be changed while dialog is showing..
        /// </summary>
        public static string EnsurePathExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureReadOnly cannot be changed while dialog is showing..
        /// </summary>
        public static string EnsureReadonlyCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureValidNames cannot be changed while dialog is showing..
        /// </summary>
        public static string EnsureValidNamesCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing to object failed..
        /// </summary>
        public static string ExplorerBrowserBrowseToObjectFailed {
            get {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExplorerBrowser failed to get current view..
        /// </summary>
        public static string ExplorerBrowserFailedToGetView {
            get {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get icon size..
        /// </summary>
        public static string ExplorerBrowserIconSize {
            get {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving item count..
        /// </summary>
        public static string ExplorerBrowserItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving selected item count..
        /// </summary>
        public static string ExplorerBrowserSelectedItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving selection..
        /// </summary>
        public static string ExplorerBrowserUnexpectedError {
            get {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving view items..
        /// </summary>
        public static string ExplorerBrowserViewItems {
            get {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path does not exist ({0}).
        /// </summary>
        public static string FilePathNotExist {
            get {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid does not identify a known folder..
        /// </summary>
        public static string FolderIdsUnknownGuid {
            get {
                return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlPanel Category.
        /// </summary>
        public static string FolderTypeCategory {
            get {
                return ResourceManager.GetString("FolderTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlPanel Classic.
        /// </summary>
        public static string FolderTypeClassic {
            get {
                return ResourceManager.GetString("FolderTypeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        public static string FolderTypeCommunications {
            get {
                return ResourceManager.GetString("FolderTypeCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed Folder.
        /// </summary>
        public static string FolderTypeCompressedFolder {
            get {
                return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string FolderTypeContacts {
            get {
                return ResourceManager.GetString("FolderTypeContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string FolderTypeDocuments {
            get {
                return ResourceManager.GetString("FolderTypeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string FolderTypeGames {
            get {
                return ResourceManager.GetString("FolderTypeGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Library.
        /// </summary>
        public static string FolderTypeGenericLibrary {
            get {
                return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string FolderTypeInvalid {
            get {
                return ResourceManager.GetString("FolderTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string FolderTypeLibrary {
            get {
                return ResourceManager.GetString("FolderTypeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string FolderTypeMusic {
            get {
                return ResourceManager.GetString("FolderTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Icons.
        /// </summary>
        public static string FolderTypeMusicIcons {
            get {
                return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Explorer.
        /// </summary>
        public static string FolderTypeNetworkExplorer {
            get {
                return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string FolderTypeNotSpecified {
            get {
                return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Search.
        /// </summary>
        public static string FolderTypeOpenSearch {
            get {
                return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Users.
        /// </summary>
        public static string FolderTypeOtherUsers {
            get {
                return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string FolderTypePictures {
            get {
                return ResourceManager.GetString("FolderTypePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        public static string FolderTypePrinters {
            get {
                return ResourceManager.GetString("FolderTypePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordedTV.
        /// </summary>
        public static string FolderTypeRecordedTV {
            get {
                return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecycleBin.
        /// </summary>
        public static string FolderTypeRecycleBin {
            get {
                return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Games.
        /// </summary>
        public static string FolderTypeSavedGames {
            get {
                return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Connector.
        /// </summary>
        public static string FolderTypeSearchConnector {
            get {
                return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches.
        /// </summary>
        public static string FolderTypeSearches {
            get {
                return ResourceManager.GetString("FolderTypeSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic SearchResults.
        /// </summary>
        public static string FolderTypeSearchResults {
            get {
                return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Explorer.
        /// </summary>
        public static string FolderTypeSoftwareExplorer {
            get {
                return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Files.
        /// </summary>
        public static string FolderTypeUserFiles {
            get {
                return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Libraries.
        /// </summary>
        public static string FolderTypeUserLibraries {
            get {
                return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string FolderTypeVideos {
            get {
                return ResourceManager.GetString("FolderTypeVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsExpandedMode cannot be changed while dialog is showing..
        /// </summary>
        public static string IsExpandedModeCannotBeChanged {
            get {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom categories cannot be added while recent documents tracking is turned off..
        /// </summary>
        public static string JumpListCustomCategoriesDisabled {
            get {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type is not registered with this application..
        /// </summary>
        public static string JumpListFileTypeNotRegistered {
            get {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpListLink&apos;s path is required and cannot be null..
        /// </summary>
        public static string JumpListLinkPathRequired {
            get {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpListLink&apos;s title is required and cannot be null..
        /// </summary>
        public static string JumpListLinkTitleRequired {
            get {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative numbers are not allowed for the ordinal position..
        /// </summary>
        public static string JumpListNegativeOrdinalPosition {
            get {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Known Folder ID is invalid..
        /// </summary>
        public static string KnownFolderInvalidGuid {
            get {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing name is invalid..
        /// </summary>
        public static string KnownFolderParsingName {
            get {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of window has failed, view inner exception for details..
        /// </summary>
        public static string MessageListenerCannotCreateWindow {
            get {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window class could not be registered, check inner exception for more details..
        /// </summary>
        public static string MessageListenerClassNotRegistered {
            get {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message filter registration failed..
        /// </summary>
        public static string MessageListenerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listener handled of that value is registered..
        /// </summary>
        public static string MessageListenerFilterUnknownListenerHandle {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create window on the listener thread because there is no existing window on the listener thread..
        /// </summary>
        public static string MessageListenerNoWindowHandle {
            get {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigateToShortcut cannot be changed while dialog is showing..
        /// </summary>
        public static string NavigateToShortcutCannotBeChanged {
            get {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent cannot be null..
        /// </summary>
        public static string NavigationLogNullParent {
            get {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        public static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverwritePrompt cannot be changed while dialog is showing..
        /// </summary>
        public static string OverwritePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This CanonicalName is not a valid index..
        /// </summary>
        public static string PropertyCollectionCanonicalInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PropertyKey is not a valid index..
        /// </summary>
        public static string PropertyCollectionInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument CanonicalName cannot be null or empty..
        /// </summary>
        public static string PropertyCollectionNullCanonicalName {
            get {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogRadioButtonList..
        /// </summary>
        public static string RadioButtonListIndexOutOfBounds {
            get {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreDirectory cannot be changed while dialog is showing..
        /// </summary>
        public static string RestoreDirectoryCannotBeChanged {
            get {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved a null shell item from dialog..
        /// </summary>
        public static string SaveFileNullItem {
            get {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given property key is invalid..
        /// </summary>
        public static string SearchConditionFactoryInvalidProperty {
            get {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Exception has occurred, look at inner exception for information..
        /// </summary>
        public static string ShellExceptionDefaultText {
            get {
                return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetParsingName has failed..
        /// </summary>
        public static string ShellHelperGetParsingNameFailed {
            get {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given CanonicalName is not valid..
        /// </summary>
        public static string ShellInvalidCanonicalName {
            get {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultSaveFolder path not found..
        /// </summary>
        public static string ShellLibraryDefaultSaveFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibraryName cannot be empty..
        /// </summary>
        public static string ShellLibraryEmptyName {
            get {
                return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path not found..
        /// </summary>
        public static string ShellLibraryFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FolderType Guid..
        /// </summary>
        public static string ShellLibraryInvalidFolderType {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given known folder is not a valid library..
        /// </summary>
        public static string ShellLibraryInvalidLibrary {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get the display name..
        /// </summary>
        public static string ShellObjectCannotGetDisplayName {
            get {
                return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array too small, or invalid arrayIndex..
        /// </summary>
        public static string ShellObjectCollectionArrayTooSmall {
            get {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one shell object in the collection..
        /// </summary>
        public static string ShellObjectCollectionEmptyCollection {
            get {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert items into a read only list..
        /// </summary>
        public static string ShellObjectCollectionInsertReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove items from a read only list..
        /// </summary>
        public static string ShellObjectCollectionRemoveReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell item could not be created..
        /// </summary>
        public static string ShellObjectCreationFailed {
            get {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Object creation requires Windows Vista or higher operating system..
        /// </summary>
        public static string ShellObjectFactoryPlatformNotSupported {
            get {
                return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Create Shell Item..
        /// </summary>
        public static string ShellObjectFactoryUnableToCreateItem {
            get {
                return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration for change notification has failed..
        /// </summary>
        public static string ShellObjectWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change watched events while listening..
        /// </summary>
        public static string ShellObjectWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property..
        /// </summary>
        public static string ShellPropertyCannotSetProperty {
            get {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor found matching requested argument types..
        /// </summary>
        public static string ShellPropertyFactoryConstructorNotFound {
            get {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set property..
        /// </summary>
        public static string ShellPropertySetValue {
            get {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get writable property store for this property..
        /// </summary>
        public static string ShellPropertyUnableToGetWritableProperty {
            get {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception..
        /// </summary>
        public static string ShellPropertyValueTruncated {
            get {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Property is available on Windows 7 only..
        /// </summary>
        public static string ShellPropertyWindows7 {
            get {
                return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property only accepts a value of type \&quot;{0}\&quot;..
        /// </summary>
        public static string ShellPropertyWrongType {
            get {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set list of sort columns..
        /// </summary>
        public static string ShellSearchFolderUnableToSetSortColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set visible columns..
        /// </summary>
        public static string ShellSearchFolderUnableToSetVisibleColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentSize (width or height) cannot be greater than the maximum size: {0}..
        /// </summary>
        public static string ShellThumbnailCurrentSizeRange {
            get {
                return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item..
        /// </summary>
        public static string ShellThumbnailDoesNotHaveThumbnail {
            get {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object..
        /// </summary>
        public static string ShellThumbnailNoHandler {
            get {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentSize (width or height) cannot be 0..
        /// </summary>
        public static string ShellThumbnailSizeCannotBe0 {
            get {
                return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowHiddenItems cannot be changed while dialog is showing..
        /// </summary>
        public static string ShowHiddenItemsCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show places list cannot be changed while dialog is showing..
        /// </summary>
        public static string ShowPlacesListCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stock Icon identifier given is invalid ({0})..
        /// </summary>
        public static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child control&apos;s window handle cannot be zero..
        /// </summary>
        public static string TabbedThumbnailZeroChildHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent window handle cannot be zero..
        /// </summary>
        public static string TabbedThumbnailZeroParentHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabbedThumbnailProxyWindow has not been set..
        /// </summary>
        public static string TasbarWindowProxyWindowSet {
            get {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid active Window is needed to update the Taskbar..
        /// </summary>
        public static string TaskbarManagerValidWindowRequired {
            get {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of buttons must contain at least 1 item..
        /// </summary>
        public static string TaskbarWindowEmptyButtonArray {
            get {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons..
        /// </summary>
        public static string TaskbarWindowManagerButtonsAlreadyAdded {
            get {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is already set. It cannot be set more than once..
        /// </summary>
        public static string TaskbarWindowValueSet {
            get {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given control has not been added to the taskbar..
        /// </summary>
        public static string ThumbnailManagerControlNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window handle is invalid..
        /// </summary>
        public static string ThumbnailManagerInvalidHandle {
            get {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This preview has already been added..
        /// </summary>
        public static string ThumbnailManagerPreviewAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given preview has not been added to the taskbar..
        /// </summary>
        public static string ThumbnailManagerPreviewNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of buttons allowed is 7..
        /// </summary>
        public static string ThumbnailToolbarManagerMaxButtons {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null or empty arrays are not allowed..
        /// </summary>
        public static string ThumbnailToolbarManagerNullEmptyArray {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }
    }
}
